on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5-branch

    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Python and Upgrade pip & west
        run: |
          apt-get update
          apt-get install -y python3.10 python3.10-venv python3.10-dev
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
          python3 -m pip install --upgrade pip
          pip install --upgrade west
        shell: bash

      - name: West Init and Update
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: West Build (Corne Left)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Corne DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp

      - name: Corne Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2 (Corne Left)
        run: cp build/zephyr/zmk.uf2 corne_left_nice_nano.uf2

      - name: Archive (Corne Left)
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: corne_left_nice_nano.uf2

      - name: West Build (Corne Right)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Corne Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2 (Corne Right)
        run: cp build/zephyr/zmk.uf2 corne_right_nice_nano.uf2

      - name: Archive (Corne Right)
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: corne_right_nice_nano.uf2
